# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * 1-5'


  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update_bsc_with_master:
    runs-on: ubuntu-latest
    steps:
    - name: forkbacon
    - uses: actions/checkout@v2
    - uses: shitiomatic/forkbacon@master # Prefer using tagged version
      with:
        upstream_url: "https://github.com/ESMValGroup/ESMValCore.git" # Required! Upstream https clone URL
        upstream_branch: "master"   # Upstream Branch to use
        branch: "bsc"   # Local Branch
        method: "rebase"   # Method to use. Can be `merge`, `merge-ff-only` or `rebase`.
        args: "--no-push"  # Additional Arguments to pass to the container
